import Head from 'next/head'
import {useState, useContext, useEffect} from 'react'
import {ClientContext} from './_app'
// import {useRouter} from 'next/router'
import Link from 'next/link';
import {Room} from 'matrix-js-sdk'

export default function Home() {
  const client = useContext(ClientContext)
  // const router = useRouter()
  const [rooms, setRooms] = useState<Room[]>([])

  client?.once('sync', function(state, prevState, res) {
    console.log(state); // state will be 'PREPARED' when the client is ready to use
    if (state === 'PREPARED') accessRooms()
  });
  
  function accessRooms() {
    setRooms(client.getRooms())    
  }
  
  //when client is logged in, then 
  
  return (
    <div>
      <Head>
        <title>Organ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>Organ</h1>
      {client?.isLoggedIn() 
        ? `Hello ${client.getUserIdLocalpart()}` 
        : <Link href="/login">Login</Link>
      }
      {rooms.map((room, i) => <p key={i}>{room.roomId}</p>)}
    </div>
  )
}
